// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataSibTerminal.Models;

public partial class Ticket
{
    public int? TicketId { get; set; }

    public string Description { get; set; }

    public string AnydeskId { get; set; }

    public int? CreationTime { get; set; }
}