// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace DataSibTerminal.Models;

public partial class Ticket
{
    public bool? Issolved { get; set; }=false;
    public string Description { get; set; }
    public string AnydeskId { get; set; }
    public double? CreationTime { get; set; }
}